# Generated by Django 4.2.18 on 2025-01-27 05:56

import logging
from typing import TYPE_CHECKING

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, transaction

logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from catalog.models import Item


def merge_to(self, to_item: "Item | None"):
    if to_item is None:
        if self.merged_to_item is not None:
            self.merged_to_item = None
            self.save()
        return
    if to_item.pk == self.pk:
        return
        raise ValueError("cannot merge to self")
    if to_item.merged_to_item is not None:
        return
        raise ValueError("cannot merge to item which is merged to another item")
    if not isinstance(to_item, self.__class__):
        raise ValueError("cannot merge to item in a different model")
    self.merged_to_item = to_item
    self.save()
    for res in self.external_resources.all():
        res.item = to_item
        res.save()
    for edition in self.editions.all():
        edition.related_work = to_item
        edition.save()
    to_item.save()


def merge_works(apps, schema_editor):
    if getattr(settings, "SKIP_WORK_MIGRATION", False):
        return
    Edition = apps.get_model("catalog", "Edition")
    # Work = apps.get_model("catalog", "Work")
    with transaction.atomic():
        for edition in Edition.objects.all():
            works = edition.works.all()
            if not works.exists():
                continue
            if edition.related_work is None:
                related_work = works.first()
                while related_work.merged_to_item is not None:
                    related_work = related_work.merged_to_item
                try:
                    edition.related_work = related_work
                    edition.save()
                except Exception as e:
                    # do not know why, some work's class will be Item and cause error
                    logger.warning(
                        f"Error setting related_work for {edition} to {related_work}: {e}"
                    )
                    continue
            for work in works:
                if work.pk == edition.related_work.pk:
                    continue
                while work.merged_to_item is not None:
                    work = work.merged_to_item
                merge_to(work, edition.related_work)


def process_pending_trigger_events(apps, schema_editor):
    # Ensure all pending trigger events are processed
    schema_editor.connection.cursor().execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_fix_soft_deleted_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="related_work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_editions",
                to="catalog.work",
            ),
        ),
        migrations.RunPython(process_pending_trigger_events),
        migrations.RunPython(merge_works),
    ]
